# Copyright 2026 Firefly Software Solutions Inc
#!/usr/bin/env python3
"""Regenerate the committed ``openapi.json`` snapshot.

The pyfly FastAPI adapter registers every controller method behind a
``lazy_endpoint(request: Request)`` shim so the DI container can
resolve the controller bean on first hit. As a side-effect FastAPI's
built-in OpenAPI introspector only sees the shim -- the real schema
is generated by :func:`flycanon.web.openapi_override.install_openapi`,
which runs inside the ASGI ``lifespan`` hook after pyfly's startup has
populated the bean context.

This script drives the same sequence in a one-shot Python process:

1. Forces safe in-memory defaults so the script can run on a clean
   checkout with no Postgres, Redis or LLM keys configured.
2. Boots :class:`PyFlyApplication` exactly the way the ASGI lifespan
   would.
3. Installs the pyfly-driven OpenAPI generator on the FastAPI app.
4. Writes the resulting spec to ``openapi.json`` at the repo root with
   ``sort_keys=True`` so the snapshot diff is stable across runs.

Run from the repo root::

    uv run python scripts/update_openapi_snapshot.py
"""

from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path


def _seed_environment() -> None:
    """Set safe defaults so the script runs on a clean checkout.

    These mirror the values the unit test sets and the CI ``unit``
    job exports, so the local regeneration produces the exact same
    spec CI checks against.
    """
    # Async-SQLAlchemy URL -- aiosqlite in-memory keeps DDL self-contained.
    os.environ.setdefault("FLYCANON_DATABASE_URL", "sqlite+aiosqlite:///:memory:")
    # Single-process EDA so the script doesn't try to dial Redis / Postgres.
    os.environ.setdefault("FLYCANON_EDA_ADAPTER", "memory")
    # Skip alembic upgrade head on startup -- pyfly's ddl-auto=create
    # builds the schema from the SQLAlchemy metadata, which is enough
    # for the openapi generator to walk every controller.
    os.environ.setdefault("RUN_MIGRATIONS", "false")
    # Dummy provider credentials so pydantic-ai providers can
    # instantiate at import time without raising.
    os.environ.setdefault("OPENAI_API_KEY", "sk-dummy-key")
    os.environ.setdefault("ANTHROPIC_API_KEY", "sk-dummy-key")
    os.environ.setdefault("AWS_DEFAULT_REGION", "eu-west-1")


async def _generate_spec() -> dict:
    """Boot the app, install the pyfly OpenAPI generator, return the spec."""
    # Lazy imports -- ``flycanon.main`` runs ``create_app`` at import time
    # so the env-seed step above must complete first.
    from flycanon import __version__
    from flycanon.main import _DESCRIPTION, _TITLE, _pyfly, app
    from flycanon.web.openapi_override import install_openapi

    await _pyfly.startup()
    try:
        install_openapi(
            app,
            _pyfly.context,
            title=_TITLE,
            version=__version__,
            description=_DESCRIPTION,
        )
        # Clear the FastAPI cache so the override generator runs.
        app.openapi_schema = None
        return app.openapi()
    finally:
        await _pyfly.shutdown()


def main() -> None:
    _seed_environment()
    spec = asyncio.run(_generate_spec())
    snapshot_path = Path(__file__).resolve().parents[1] / "openapi.json"
    # ``sort_keys=True`` keeps the snapshot diff stable across runs;
    # ``indent=2`` makes the file reviewable in PR diffs.
    snapshot_path.write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n")
    paths = len(spec.get("paths", {}))
    schemas = len((spec.get("components") or {}).get("schemas", {}))
    print(f"Wrote {snapshot_path} ({paths} paths, {schemas} schemas)")


if __name__ == "__main__":
    main()
