# Copyright 2024-2026 Firefly Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""flycanon Python SDK -- async client for the Operational Knowledge
Repository service."""

from __future__ import annotations

from flycanon_sdk._client import AgentSurface, CanonClient
from flycanon_sdk._errors import (
    AgentCannotMint,
    AgentScopeDenied,
    AgentTokenExpired,
    AgentWorkspaceNotInAllowlist,
    CanonAPIError,
    CanonConnectionError,
    CanonError,
    FieldError,
    InvalidAgentToken,
    MissingAgentToken,
    MissingIdempotencyKey,
    ValidationError,
)
from flycanon_sdk._models import (
    CANON_WORKSPACES_TOPIC,
    AcceptCandidateRequest,
    AgentTokenCreated,
    AgentTokenMintRequest,
    AgentTokenSummary,
    AnswerRequest,
    AnswerResponse,
    AuditEvent,
    AuditPage,
    BillingReport,
    BillingRow,
    BillingSummary,
    BillingWindow,
    BulkSourceResult,
    BulkSourcesResponse,
    CandidateRecord,
    CandidatesPage,
    CandidateStats,
    ChunkStats,
    Citation,
    ConflictScanRequest,
    ConflictScanResponse,
    Conversation,
    ConversationHeader,
    ConversationTurn,
    CorpusStats,
    CostEvent,
    CostEventsPage,
    CostStreamStats,
    CreateConversationRequest,
    CreateConversationTurnRequest,
    CreateKnowledgeRequest,
    CreateRelationRequest,
    CreateTaxonomyNodeRequest,
    GraphEdge,
    GraphNode,
    Hit,
    IngestJob,
    IngestJobEvent,
    JobStats,
    KnowledgeDiff,
    KnowledgeFieldChange,
    KnowledgeGraph,
    KnowledgeItem,
    KnowledgeItemsPage,
    KnowledgeItemStats,
    KnowledgeRelation,
    KnowledgeVersion,
    LatencyReport,
    LatencyRow,
    ProblemDetails,
    ProposeCandidateRequest,
    Provenance,
    RejectCandidateRequest,
    RelationsList,
    RetireKnowledgeRequest,
    SearchRequest,
    SearchResponse,
    SourceMetadata,
    SourceRecord,
    SourcesPage,
    SourceStats,
    StaleItem,
    StaleReport,
    SubjectCostReport,
    SubjectCostRow,
    SubmitSourceJsonPayload,
    SuggestionsResponse,
    SupersedeKnowledgeRequest,
    TaxonomyNode,
    TaxonomyTree,
    TopConsumerRow,
    TopConsumersReport,
    UpdateKnowledgeRequest,
    VersionInfo,
    WorkspaceCreate,
    WorkspaceCreated,
    WorkspaceDeleted,
    WorkspaceSpec,
    WorkspaceSummary,
    WorkspaceUpdate,
    WorkspaceUpdated,
)

__version__ = "26.5.7"

__all__ = [
    "CANON_WORKSPACES_TOPIC",
    "AcceptCandidateRequest",
    "AgentCannotMint",
    "AgentScopeDenied",
    "AgentSurface",
    "AgentTokenCreated",
    "AgentTokenExpired",
    "AgentTokenMintRequest",
    "AgentTokenSummary",
    "AgentWorkspaceNotInAllowlist",
    "AnswerRequest",
    "AnswerResponse",
    "AuditEvent",
    "AuditPage",
    "BillingReport",
    "BillingRow",
    "BillingSummary",
    "BillingWindow",
    "BulkSourceResult",
    "BulkSourcesResponse",
    "CanonAPIError",
    "CanonClient",
    "CanonConnectionError",
    "CanonError",
    "CandidateRecord",
    "CandidateStats",
    "CandidatesPage",
    "ChunkStats",
    "Citation",
    "ConflictScanRequest",
    "ConflictScanResponse",
    "Conversation",
    "ConversationHeader",
    "ConversationTurn",
    "CorpusStats",
    "CostEvent",
    "CostEventsPage",
    "CostStreamStats",
    "CreateConversationRequest",
    "CreateConversationTurnRequest",
    "CreateKnowledgeRequest",
    "CreateRelationRequest",
    "CreateTaxonomyNodeRequest",
    "FieldError",
    "GraphEdge",
    "GraphNode",
    "Hit",
    "IngestJob",
    "IngestJobEvent",
    "InvalidAgentToken",
    "JobStats",
    "KnowledgeDiff",
    "KnowledgeFieldChange",
    "KnowledgeGraph",
    "KnowledgeItem",
    "KnowledgeItemStats",
    "KnowledgeItemsPage",
    "KnowledgeRelation",
    "KnowledgeVersion",
    "LatencyReport",
    "LatencyRow",
    "MissingAgentToken",
    "MissingIdempotencyKey",
    "ProblemDetails",
    "ProposeCandidateRequest",
    "Provenance",
    "RejectCandidateRequest",
    "RelationsList",
    "RetireKnowledgeRequest",
    "SearchRequest",
    "SearchResponse",
    "SourceMetadata",
    "SourceRecord",
    "SourceStats",
    "SourcesPage",
    "StaleItem",
    "StaleReport",
    "SubjectCostReport",
    "SubjectCostRow",
    "SubmitSourceJsonPayload",
    "SuggestionsResponse",
    "SupersedeKnowledgeRequest",
    "TaxonomyNode",
    "TaxonomyTree",
    "TopConsumerRow",
    "TopConsumersReport",
    "UpdateKnowledgeRequest",
    "ValidationError",
    "VersionInfo",
    "WorkspaceCreate",
    "WorkspaceCreated",
    "WorkspaceDeleted",
    "WorkspaceSpec",
    "WorkspaceSummary",
    "WorkspaceUpdate",
    "WorkspaceUpdated",
    "__version__",
]
