# Copyright 2026 Firefly Software Solutions Inc
"""flycanon Python SDK -- async client for the Operational Knowledge
Repository service."""

from __future__ import annotations

from flycanon_sdk._client import CanonClient
from flycanon_sdk._errors import CanonAPIError, CanonConnectionError
from flycanon_sdk._models import (
    AcceptCandidateRequest,
    AnswerRequest,
    AnswerResponse,
    AuditEvent,
    AuditPage,
    BillingReport,
    BillingRow,
    BulkSourceResult,
    BulkSourcesResponse,
    CandidateRecord,
    CandidatesPage,
    Citation,
    ConflictScanRequest,
    ConflictScanResponse,
    Conversation,
    ConversationHeader,
    ConversationTurn,
    CreateConversationRequest,
    CreateConversationTurnRequest,
    CreateKnowledgeRequest,
    CreateRelationRequest,
    CreateTaxonomyNodeRequest,
    GraphEdge,
    GraphNode,
    Hit,
    IngestJob,
    IngestJobEvent,
    KnowledgeDiff,
    KnowledgeFieldChange,
    KnowledgeGraph,
    KnowledgeItem,
    KnowledgeItemsPage,
    KnowledgeRelation,
    KnowledgeVersion,
    ProblemDetails,
    ProposeCandidateRequest,
    Provenance,
    RejectCandidateRequest,
    RelationsList,
    RetireKnowledgeRequest,
    SearchRequest,
    SearchResponse,
    SourceMetadata,
    SourceRecord,
    SourcesPage,
    StaleItem,
    StaleReport,
    SubmitSourceJsonPayload,
    SuggestionsResponse,
    SupersedeKnowledgeRequest,
    TaxonomyNode,
    TaxonomyTree,
    UpdateKnowledgeRequest,
    VersionInfo,
)

__version__ = "26.5.2"

__all__ = [
    "AcceptCandidateRequest",
    "AnswerRequest",
    "AnswerResponse",
    "AuditEvent",
    "AuditPage",
    "BillingReport",
    "BillingRow",
    "BulkSourceResult",
    "BulkSourcesResponse",
    "CanonAPIError",
    "CanonClient",
    "CanonConnectionError",
    "CandidateRecord",
    "CandidatesPage",
    "Citation",
    "ConflictScanRequest",
    "ConflictScanResponse",
    "Conversation",
    "ConversationHeader",
    "ConversationTurn",
    "CreateConversationRequest",
    "CreateConversationTurnRequest",
    "CreateKnowledgeRequest",
    "CreateRelationRequest",
    "CreateTaxonomyNodeRequest",
    "GraphEdge",
    "GraphNode",
    "Hit",
    "IngestJob",
    "IngestJobEvent",
    "KnowledgeDiff",
    "KnowledgeFieldChange",
    "KnowledgeGraph",
    "KnowledgeItem",
    "KnowledgeItemsPage",
    "KnowledgeRelation",
    "KnowledgeVersion",
    "ProblemDetails",
    "ProposeCandidateRequest",
    "Provenance",
    "RejectCandidateRequest",
    "RelationsList",
    "RetireKnowledgeRequest",
    "SearchRequest",
    "SearchResponse",
    "SourceMetadata",
    "SourceRecord",
    "SourcesPage",
    "StaleItem",
    "StaleReport",
    "SubmitSourceJsonPayload",
    "SuggestionsResponse",
    "SupersedeKnowledgeRequest",
    "TaxonomyNode",
    "TaxonomyTree",
    "UpdateKnowledgeRequest",
    "VersionInfo",
    "__version__",
]
