# Copyright 2026 Firefly Software Solutions Inc
"""ASGI entry point for flycanon.

Loaded by ``flycanon serve`` and by ``uvicorn flycanon.main:app``.
Builds the :class:`PyFlyApplication`, scans every ``@rest_controller``,
``@configuration``, ``@service``, ``@controller_advice``,
``@command_handler`` and ``@query_handler`` under ``flycanon``, and
returns a FastAPI app with all routes mounted, the actuator + admin
exposed, exception handlers wired, and the OpenAPI spec generated by
pyfly's introspector.
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from typing import Any

from pyfly.core import PyFlyApplication
from pyfly.web.adapters.fastapi.app import create_app

from flycanon import __version__
from flycanon.app import CanonApplication
from flycanon.web.openapi_override import install_openapi
from flycanon.web.problem_handlers import register_problem_handlers

_TITLE = "flycanon"
_DESCRIPTION = (
    "Operational Knowledge Repository -- versioned, provenance-tracked "
    "canonical knowledge with hybrid retrieval (BM25 + vector + RRF) "
    "and retrieval-augmented answering, exposed as a standalone HTTP "
    "microservice over fireflyframework-pyfly and -agentic. Part of "
    "Firefly OperationOS, platform-agnostic by design."
)

# Build PyFlyApplication: loads pyfly.yaml, scans packages, prepares the
# DI context.
_pyfly = PyFlyApplication(CanonApplication)


@asynccontextmanager
async def _lifespan(app: Any):
    """Drive the framework's startup / shutdown lifecycle.

    Also installs the pyfly-driven OpenAPI generator after startup, so
    Swagger / ReDoc see the real controller signatures (tags, request
    bodies, response models) instead of the lazy-resolution shim that
    pyfly registers with FastAPI.
    """
    # PyFlyApplication exposes route metadata + host/port via private
    # attributes that the framework's own lifespan flow writes to; we
    # mirror that here so pyfly's structured-logging "server_started"
    # event reports the right host/port.
    setattr(_pyfly, "_route_metadata", getattr(app.state, "pyfly_route_metadata", []))  # noqa: B010
    setattr(_pyfly, "_docs_enabled", getattr(app.state, "pyfly_docs_enabled", False))  # noqa: B010
    setattr(_pyfly, "_host", str(_pyfly.config.get("pyfly.web.host", "0.0.0.0")))  # noqa: B010
    setattr(_pyfly, "_port", int(_pyfly.config.get("pyfly.server.port", 8500)))  # noqa: B010
    await _pyfly.startup()
    # Re-scan HealthIndicator beans now that the container has built
    # every singleton (the eager scan inside ``create_app`` runs BEFORE
    # context startup and would otherwise miss every indicator wired
    # through @auto_configuration).
    rescan = getattr(app.state, "pyfly_install_health_indicators", None)
    if callable(rescan):
        rescan()
    install_openapi(
        app,
        _pyfly.context,
        title=_TITLE,
        version=__version__,
        description=_DESCRIPTION,
    )
    yield
    await _pyfly.shutdown()


app = create_app(
    title=_TITLE,
    version=__version__,
    description=_DESCRIPTION,
    context=_pyfly.context,
    docs_enabled=True,
    actuator_enabled=True,
    lifespan=_lifespan,
)
# pyfly's FastAPI adapter only walks controller-LOCAL exception
# handlers, so the @controller_advice surface never fires. Register
# the same handler table directly with FastAPI; this also unwraps
# CommandProcessingException / QueryProcessingException so the typed
# domain exception raised by the service layer keeps its HTTP status
# + RFC 7807 code instead of being flattened to 400 COMMAND_PROCESSING_ERROR.
register_problem_handlers(app)
# The W3C correlation surface (X-Correlation-Id / X-Request-Id /
# X-Tenant-Id / traceparent / tracestate) is wired into pyfly's default
# WebFilter chain via
# ``pyfly.web.adapters.starlette.filters.CorrelationFilter`` -- no extra
# middleware to register here.
